apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce
type: Opaque
stringData:
  JWT_SECRET: "change-this-in-production-use-vault"
  JWT_REFRESH_SECRET: "change-this-refresh-secret-in-production"
  MONGODB_URI: "mongodb://mongodb:27017"
  STRIPE_SECRET_KEY: "sk_test_placeholder"

